version: '3.8'

services:
  black_hole:
    container_name: black_hole
    image: monkeyhouse1/black_hole:${TAG:-latest}
    privileged: true
    pid: host
    ports:
      - "9080:9080"
    env_file: ${ENV_FILE}
    build:
      dockerfile: Dockerfile
      args:
        BRANCH: develop
