basePath: /
definitions:
  types.JobError:
    properties:
      code:
        type: string
      description:
        type: string
    type: object
  types.JobListItem:
    properties:
      created_at:
        type: integer
      id:
        type: string
      payload:
        $ref: '#/definitions/types.JobRequest'
      result:
        $ref: '#/definitions/types.JobResponse'
    type: object
  types.JobRequest:
    properties:
      action:
        maxLength: 2048
        minLength: 1
        type: string
      arguments:
        items:
          type: string
        type: array
      id:
        maxLength: 100
        minLength: 2
        type: string
      timeout:
        default: 1000
        type: integer
      type:
        enum:
        - embedded
        - related
        - absolute
        type: string
    required:
    - action
    - arguments
    - id
    - timeout
    - type
    type: object
  types.JobResponse:
    properties:
      error:
        $ref: '#/definitions/types.JobError'
      status:
        enum:
        - run
        - error
        - finish
        type: string
    type: object
  utils.HttpError:
    properties:
      code:
        type: string
      description:
        type: string
      validation: {}
    type: object
host: localhost:9080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample API with Swagger documentation.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: My API
  version: "1.0"
paths:
  /job:
    post:
      consumes:
      - application/json
      description: Returns job id
      parameters:
      - description: Job request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.JobRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/utils.HttpError'
      summary: Run job
      tags:
      - job
  /job/{id}:
    get:
      consumes:
      - application/json
      description: Returns job info
      parameters:
      - description: Job id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.JobListItem'
      summary: Get job
      tags:
      - job
swagger: "2.0"
